# Generated by Django 4.2.7 on 2024-01-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='vbjbj', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
